import React, { useState, useEffect } from 'react';

import range from 'lodash/range';
import random from 'lodash/random';

function About() {
  const [seconds, setSeconds] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setSeconds(seconds => seconds + 1);
    }, 2000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="container">
      <main className="side-page">
        { 
          range(1).map(() => (
            <img 
              className="about-img" 
              src="/img/adorableBeastInsta.jpg" 
              style={{
                top: `${random(100)}%`,
                left: `${random(100)}%`,
                width: `${random(10, 25)}vw`,
                height: `${random(10, 25)}vw`,
                opacity: `${random(0.1, 1.0)}`
              }}
            />
          )) 
        }
        <div className="about-text">
          <p>In every process of evolution, there is a period of extreme contamination that lends the possibility for the trajectories of species to begin to mutate. In the last 30 years, design has experienced multiple paradigm shifts generated by an eruption of new methodologies. These were derived mainly from new technologies, but also from a series of cultural changes, each prompting a reorganization in the culture of design, architecture, and art, and violating an old order, rendering it historical, obsolete.</p>

          <p>Today, perhaps as never before, we share a technical language that flows from discipline to discipline, altering the paths of previously discrete branches of knowledge. Many practices—art, architecture, fashion, film, music—explore similar ambitions, ideas rippling across and among them. The notion of authorship itself is in flux.</p>

          <p>This exhibition acknowledges and propels this phenomenon. It seeks to carve a path through a jungle of aesthetic and conceptual similarities to provoke contamination. Through artificial intelligence, the work featured will be exposed to a perpetual state of transformation and mutation. The exhibition gathers a key set of practices, primarily from architecture, but also from art and fashion, to reveal facets of the strange beast that the tumultuous paradigm shifts of recent decades have left behind.</p>
        </div>
      </main>
    </div>
  )
}

export default About;