export default ["a view of a large body of water.",
"a couple of giraffe standing next to each other.",
"a large tree in the middle of a forest.",
"a large tree in the middle of a forest.",
"a giraffe standing in the grass next to a tree.",
"a close up of a giraffe in a field.",
"a group of people standing in front of a group of motorcycles.",
"a bunch of flowers that are in a tree.",
"a couple of birds flying over a body of water.",
"a close up of a person holding an umbrella.",
"a close up of a snow covered mountain.",
"a snow covered forest covered in snow.",
"a man is doing a trick on a skateboard.",
"a close up of a snow covered mountain.",
"a close up of a bunch of stuffed animals.",
"a group of people standing in a field.",
"a person holding a kite in the air.",
"a bunch of colorful flowers in a field.",
"a bunch of birds sitting on top of a lush green field.",
"a group of animals standing in a field.",
"a group of giraffes standing next to each other.",
"a group of giraffe standing next to each other.",
"a large body of water with lots of birds.",
"a group of giraffes standing next to each other.",
"a close up of a giraffe in a field.",
"a vase filled with flowers in a vase.",
"a group of people standing in front of a christmas tree.",
"a group of people standing around a tree.",
"a group of people standing in a field.",
"a close up of a plate of food.",
"a close up of a piece of cake.",
"a snow covered mountain with a snow covered mountain.",
"a close up of a sheep in the snow.",
"a close up of a sheep in the snow.",
"a close up of a person with a cow.",
"a close up of a bunch of bananas.",
"a bunch of flowers are in a tree.",
"a picture of a giraffe in a field.",
"a person flying a kite in a field.",
"a black and white photo of a giraffe.",
"a group of people standing next to each other.",
"a large giraffe standing in the grass.",
"a group of giraffes standing next to each other.",
"a close up of a giraffe in the grass.",
"a couple of birds that are standing in the grass.",
"a group of people standing in front of a christmas tree.",
"a group of people that are in a field.",
"a bunch of stuffed animals in a room.",
"a close up of a plate of food.",
"a close up of a plate of food.",
"a close up of a piece of cake.",
"a close up of a sheep in the snow.",
"a close up of a sheep in the snow.",
"a white and white photo of a bird on the ground.",
"a close up of a plate of food.",
"a group of birds are standing in the grass.",
"a picture of a giraffe in a field.",
"a person standing in front of a window.",
"a view of a city street with a bus.",
"a black and white photo of a street.",
"a black and white photo of a city street.",
"an old photo of an old building.",
"a picture of a giraffe in a field.",
"a close up of a giraffe in a field.",
"a group of people standing in front of a christmas tree.",
"a group of people sitting on a motorcycle.",
"a group of people that are standing in the snow.",
"a group of people standing next to each other.",
"a bunch of stuffed animals in a room.",
"a close up of a bunch of bananas.",
"a close up of a piece of cake.",
"a close up of a bird on a beach.",
"a black and white photo of a bird in the water.",
"a close up of a close up of a snow covered mountain.",
"a couple of birds sitting on top of a lush green field.",
"a couple of giraffes standing in a field.",
"a black and white photo of a street.",
"a view of a snow covered mountain.",
"a view of a snowy mountain with mountains in the background.",
"a view of a snowy mountain with mountains in the background.",
"a white and white bird is standing in the grass.",
"a group of people standing in a field.",
"a crowd of people standing around a tree.",
"a close up of a bunch of bananas.",
"a group of people that are standing in the snow.",
"a group of people that are standing in the snow.",
"a person is holding a piece of pizza.",
"a close up of a person holding a knife.",
"a close up of a person holding a glass of wine.",
"a bunch of different types of flowers in a vase.",
"a close up of a plate of food.",
"a group of birds flying in the sky.",
"a close up of a pizza on a plate.",
"a flock of birds flying in the air.",
"a giraffe is standing in the middle of a field.",
"a train traveling down the tracks near a mountain.",
"a view of a mountain with mountains in the background.",
"a bunch of birds are in the grass.",
"a close up of a plate of food.",
"a close up of a bunch of bananas.",
"a close up of a bunch of flowers.",
"a group of people standing in the snow.",
"a street scene with a clock tower in the background.",
"a bunch of flowers in a dark room.",
"a close up of a person holding a cell phone.",
"a person is looking at a laptop computer.",
"a person holding a remote control in their hand.",
"a person standing in front of a red fire hydrant.",
"a close up of a bunch of bananas.",
"a close up of a bunch of flowers.",
"a bunch of birds flying in the sky.",
"a person flying a kite in a field.",
"a flock of birds flying in the air.",
"a group of people sitting on top of a bench.",
"a train that is sitting on the tracks.",
"a close up of a snow covered hillside.",
"a close up of a plate of food.",
"a close up of a plate of food.",
"a close up of a plate of food.",
"a close up of a person holding a knife.",
"a person holding a pair of scissors in their hand.",
"a person is playing with a remote control.",
"a person sitting on a bed with a laptop.",
"a black and white photo of a dark room.",
"a close up of a person holding a remote.",
"a close up of a person on a couch.",
"a close up of a pair of scissors.",
"a close up of a plate of food.",
"a close up of a bunch of flowers.",
"a view of a tree in the woods.",
"a close up of a giraffe in a field.",
"a person standing in front of a tree.",
"a close up of a piece of cake.",
"a snow covered field with a snow covered mountain.",
"a close up of a plate of food.",
"a close up of a plate of food.",
"a close up of a plate of food.",
"a close up of a plate of food.",
"a group of people standing in front of a christmas tree.",
"a person is holding a piece of pizza.",
"a person is looking at the camera.",
"a blurry photo of a person holding a cell phone.",
"a blurry photo of a blurry image of a person.",
"a picture of a person in a dark room.",
"a blurry photo of a person in a dark room.",
"a blurry photo of a person in a dark room.",
"a bunch of flowers sitting on top of a lush green field.",
"a small bird is standing in the grass.",
"a close up of a giraffe in a field.",
"a couple of giraffe standing next to each other.",
"a group of people standing in a field.",
"a group of sheep standing on top of a lush green field.",
"a person standing on a snow covered slope.",
"a close up of a piece of cake.",
"a close up of a plate of food.",
"a bunch of birds flying in the air.",
"a man riding a motorcycle with a crowd of people.",
"a close up of a bunch of bananas.",
"a blurry photo of a person in a dark room.",
"a close up of a person holding a remote.",
"a close up of a bunch of vegetables.",
"a group of people sitting on a bench.",
"a group of people standing next to each other.",
"a close up of a person holding a cell phone.",
"a bunch of flowers in a vase on a table.",
"a group of people that are standing in the grass.",
"a bird is standing on a tree branch.",
"a giraffe standing in the middle of a field.",
"a couple of giraffes standing in a field.",
"a person is flying a kite in a park.",
"a bunch of flowers in a vase on a table.",
"a couple of birds that are standing in a room.",
"a close up of a white teddy bear.",
"a group of people that are standing in the grass.",
"a view of a tree in the woods.",
"a bird is standing in the middle of a forest.",
"a group of people that are standing in the grass.",
"a black and white photo of a person holding a remote.",
"a group of people standing in front of a tree.",
"a close up of a bunch of kites.",
"a group of people sitting on a motorcycle.",
"a group of people standing in the rain.",
"a close up of a vase filled with flowers.",
"a group of people standing on top of a lush green field.",
"a couple of teddy bears sitting on top of a bed.",
"a couple of giraffes standing next to each other.",
"a group of people standing on top of a lush green field.",
"a person standing on a lush green field.",
"a couple of birds flying in the air.",
"a bunch of colorful flowers in a field.",
"a white refrigerator sitting next to a window.",
"a close up of a piece of cake.",
"a group of people standing in front of a tree.",
"a group of people standing on top of a lush green field.",
"a couple of birds that are standing in the grass.",
"a couple of birds sitting on top of a lush green field.",
"a dark dark room with a dark light.",
"a group of people standing in front of a christmas tree.",
"a close up of a bunch of bananas.",
"a group of people sitting around a table.",
"a group of people standing in a field.",
"a bunch of stuffed animals sitting on top of a table.",
"a group of people that are standing in the grass.",
"a person standing in a field with a tree.",
"a close up of a giraffe in a field.",
"a group of giraffes standing next to each other.",
"a bird is standing in the middle of the water.",
"a group of people standing on top of a lush green field.",
"a person is doing a trick on a skateboard.",
"a black and white photo of a dark room.",
"a close up of a snow covered beach.",
"a close up of a plate of food.",
"a bunch of birds flying in the sky.",
"a black and white photo of a dog in the grass.",
"a white and white cat laying on top of a lush green field.",
"a blurry photo of a person in a dark room.",
"a group of people standing in front of a christmas tree.",
"a bunch of birds that are in a tree.",
"a group of people standing around a tree.",
"a group of people that are standing in the grass.",
"a person in a field with a frisbee.",
"a couple of birds standing on top of a lush green field.",
"a group of people standing in a field.",
"a group of people that are standing in the grass.",
"a couple of birds that are standing in the grass.",
"a group of people that are standing in the grass.",
"a bunch of birds flying in the air.",
"a close up of a piece of pizza.",
"a person standing on a sidewalk with a suitcase.",
"a black and white photo of a person on a bench.",
"a close up of a snow covered mountain.",
"a group of people are flying a kite.",
"a close up of a plate of food.",
"a group of people sitting around a table.",
"a dark room with a dark wall.",
"a person is flying a kite in a field.",
"a giraffe standing next to a stone wall.",
"a close up of a slice of pizza.",
"a close up of a piece of cake.",
"a group of people standing around a fence.",
"a group of people standing in a field.",
"a bunch of stuffed animals sitting on a table.",
"a group of people that are standing around.",
"a group of people standing around a bunch of motorcycles.",
"a close up of a plate of food.",
"a close up of a snow covered mountain.",
"a snow covered slope with a tree in the background.",
"a black and white photo of a person on a bed.",
"a large stone wall with a stone wall.",
"a picture of a person on a bench.",
"a close up of a giraffe in the snow.",
"a picture of a giraffe in a field.",
"a picture of a person on a skateboard.",
"a black and white photo of a fire hydrant.",
"a giraffe standing in front of a fence.",
"a man standing in front of a stone wall.",
"a close up of a giraffe in a field.",
"a couple of birds that are standing in the water.",
"a group of birds that are standing in the grass.",
"a close up of a plate of food.",
"a close up of a plate of food.",
"a close up of a plate of food.",
"a close up of a bunch of flowers.",
"a close up of a plate of food.",
"a close up of a snow covered mountain.",
"a snow covered forest with a tree in the background.",
"a group of people sitting on top of a lush green field.",
"a group of giraffes standing next to each other.",
"a picture of a giraffe in a field.",
"a group of people standing next to each other.",
"a black and white photo of a stone wall.",
"a large stone wall with a stone wall.",
"a view of a snow covered mountain.",
"a picture of a giraffe in a field.",
"a picture of a giraffe in a field.",
"a large teddy bear laying on a bed.",
"a person flying a kite in the air.",
"a group of people standing in front of a tree.",
"a close up of a piece of cake.",
"a close up of a plate of food.",
"a close up of a plate of food.",
"a close up of a person in a dark room.",
"a black and white photo of a cake.",
"a snow covered field with a clock on it.",
"a tree with a tree in the background.",
"a bunch of oranges are sitting on a table.",
"a man flying a kite in a park.",
"a picture of a person standing in front of a building.",
"a person standing on top of a sandy beach.",
"a train traveling down a track near a river.",
"a picture of a giraffe in a field.",
"a giraffe standing next to a stone wall.",
"a group of animals standing in a field.",
"a close up of a giraffe in a field.",
"a group of giraffes standing on top of a lush green field.",
"a small bird is standing in the grass.",
"a close up of a plate of food.",
"a close up of a person on a snowboard.",
"a close up of a snow covered mountain.",
"a close up of a person on a bed.",
"a person standing in front of a television.",
"a black and white photo of a dog laying on a bed.",
"a group of people standing on top of a snow covered slope.",
"a close up of a snow covered mountain.",
"a close up of a plate of food.",
"a black and white photo of a stone wall.",
"an old photo of a train on the tracks.",
"a black and white photo of a city street.",
"a train that is sitting on the tracks.",
"an old photo of a large stone wall.",
"a close up of a giraffe in a field.",
"a close up of a plate of food.",
"a group of people that are standing in the grass.",
"a bunch of birds sitting on top of a tree.",
"a close up of a plate of food.",
"a close up of a piece of cake.",
"a close up of a person on a snowboard.",
"a close up of a plate of food.",
"a close up of a piece of cake.",
"a person is flying a kite in the sky.",
"a close up of a snow covered hillside.",
"a picture of a giraffe in a zoo.",
"a close up of a giraffe in a field.",
"a snow covered mountain with a snow covered mountain.",
"a snow covered mountain with snow covered mountains.",
"a snow covered mountain with a mountain in the background.",
"a view of a city street with a bus.",
"a snow covered slope with a mountain in the background.",
"a view of a snow covered mountain.",
"a bunch of stuffed animals sitting on top of a snow covered field.",
"a close up of a piece of cake.",
"a close up of a piece of cake.",
"a black and white photo of a white teddy bear.",
"a close up of a person on a snowboard.",
"a close up of a piece of cake.",
"a close up of a close up of a person's hand.",
"a close up of a plate of food.",
"a close up of a plate of food.",
"a person standing in the snow with a snowboard.",
"a black and white photo of a clock tower.",
"a group of birds sitting on top of a rock.",
"a person standing in front of a stone building.",
"a group of people standing in the snow.",
"a snow covered slope with snow covered snow.",
"a view of a building with a building in the background.",
"a person walking down a street with an umbrella.",
"there is a picture of a person standing in the snow.",
"a close up of a snow covered mountain.",
"a couple of birds that are standing in the snow.",
"a white cat laying on top of a bed.",
"a person on a skateboard in the air.",
"a person flying a kite in the air.",
"a couple of birds sitting on top of a snow covered slope.",
"a cat laying on top of a bed.",
"a close up of a plate of food.",
"a close up of a plate of food.",
"a close up of a piece of cake.",
"a snow covered field with a lot of snow.",
"a man is standing on a rock in the water.",
"a white bird flying in the air over a tree.",
"a bunch of birds sitting on top of a lush green field."
]